CREATE TABLE `mountains`(
`id` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`name` VARCHAR(50) NOT NULL
);

CREATE TABLE `peaks`(
`id` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
`name` VARCHAR(50) NOT NULL,
`mountain_id` INT NOT NULL
);

ALTER TABLE `peaks`
ADD CONSTRAINT `fk_peaks_mointains`
FOREIGN KEY(`mountain_id`)
REFERENCES `mountains`(`id`);